### ISSUE TITLE
도커 관련 설정 방법들

### ISSUE THREAD

**Issue by Zamoca42** [pre-onboarding-backend-G/team-g-project-skeleton#14]
##  이슈 내용

설정 방법들을 기록으로 남겨놓습니다

<br>

##  작업 사항

- [ ] postgresql 관련 설정 추가

<br>

## 기타사항

<br>

**Comment by Zamoca42** [comment]
# feed-me-baby에서 사용했던 postgresql과 pgadmin에 관한 설정

> 리포지토리 링크: https://github.com/pre-onboarding-backend-G/feed-me-baby

## 커밋 템플릿 적용 방법

```bash
# 로컬 환경에서 커밋 템플릿 적용
git config --local commit.template .gitmessage.txt

# 커밋 템플릿으로 커밋
git commit
```

## vscode 확장앱 설치

<img width="1635" alt="스크린샷 2023-10-27 오후 10 16 17" src="https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/eda1da6a-d3f1-4af4-adb4-6e84f6f3c87a">

## 처음 로컬 환경에서 도커 시작

```bash
# 패키지 설치
npm install
# 빌드 후 시작
docker compose up --build
# 빌드가 완료되면 도커 종료
```

![스크린샷 2023-11-01 오후 12 52 33](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/ecde9923-53a3-42f7-9daa-152f63592510)

## DevContainer로 시작

- [DevContainer란?](https://zamoca42.github.io/blog/etc/docker/dev-container.html)

1. 명령팔레트에서 `F1` 누르고 컨테이너 다시 빌드하고 다시 열기 선택

    ![스크린샷 2023-11-01 오후 12 58 45](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/382597d1-1f83-44f6-95ab-eb819efdc74b)

2. 기다리기 (오래 걸림)

3. 왼쪽 아래 상태바를 확인

    ![스크린샷 2023-11-01 오후 12 47 10](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/df9c1158-aaa1-4a87-9550-3df51ce45aac)

## Nest - TypeORM - Postgres 설정 과정 요약

- [NestJS-TypeORM 문서](https://docs.nestjs.com/recipes/sql-typeorm#getting-started)

postgresql 연결 확인

![스크린샷 2023-11-01 오후 1 55 44](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/70c52f8f-8e06-4c9f-b3e9-d6ac0a92efc5)

pgadmin에 postgresql 연결

![스크린샷 2023-11-01 오후 2 06 18](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/20cb6666-8612-4325-818e-02df7220be23)

pgadmin 연결 확인

![스크린샷 2023-11-01 오후 2 06 48](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/3e0fde53-64c4-4894-b81a-d2ce20f5b60b)

nest 연결 확인

![스크린샷 2023-11-01 오후 2 17 51](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/96982072/7214da31-ce47-4d02-a15b-f94bf1ec70cb)

**Comment by Zamoca42** [comment]
## 개인 의견

- pgadmin 같은 경우에는 로그를 많이 띄우기 때문에 로그를 띄우지 않는 설정을 추가하거나 pgadmin 자체를 제외해도 될거 같음.
- linux는 alpine 버전이 가볍다.
- 처음에 패키지를 설치하지 않으면 도커 내부에서 패키지를 찾지못한다.

##  docker-compose.yml (with postgresql)

```yaml
version: '3.9'

volumes:
  postgres: {}

services:  
  database:
    container_name: feed-me-baby-postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - './postgres:/var/lib/postgresql/data'

  pgadmin:
    container_name: feed-me-baby-pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - mynetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5050:80"
    
  nest-app:
    container_name: feed-me-baby-NestJS
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    ports:
    # app port
      - '3000:3000'
    # debugging port
      - '9229:9229'
    volumes:
      - .:/usr/src/app
    # npm run start
    # npm run start:debug -> this is debugging mode
    command: npm run start
    depends_on:
      - database
    networks:
      - mynetwork
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: ${DATABASE_HOST}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      
networks:
  mynetwork:
```

## pgadmin 설정
```yaml
  pgadmin:
    container_name: dump-in-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '5555:80'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      TZ: Asia/Seoul
    depends_on:
      - database
```

**Comment by Zamoca42** [comment]
### postgresql

```yaml
  database:
    container_name: dump-in-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      TZ: Asia/Seoul
    networks:
      - mynetwork
    volumes:
      - './postgres:/var/lib/postgresql/data'
    ports:
      - '5433:5432'
```
